Improve error message when missing raw key (#796)
If a user tries to insert a raw row without specifying key, the current error message is somewhat cryptic since there is an internal KeyError during the error handling, so
```
client.raw.rows.insert("tb", "table", Row(key=None, columns={"Key": "Hello"}), ensure_parent=True)
```
fails with `KeyError: 'key'` and not a `CogniteAPIError`. With this change it would give 
```
CogniteAPIError: The request body was invalid. | code: 400 | X-Request-ID: None
The API Failed to process some items.
Successful (2xx): []
Unknown (5xx): []
Failed (4xx): [None]
```
instead.

Update changelog and version number